#!/bin/bash
# VLM Game Understanding — Rename from xlsx map
# 101 renames, 3 collision chains handled via temp names
#
# Usage:
#   bash rename_from_xlsx.sh --dry-run
#   bash rename_from_xlsx.sh

DRY_RUN=false
[[ "$1" == "--dry-run" ]] && DRY_RUN=true

SKIPPED=0; RENAMED=0; ERRORS=0

do_rename() {
  local src="$1" dst="$2"
  if [ ! -f "$src" ]; then echo "  SKIP (not found): $src"; ((SKIPPED++)); return; fi
  if $DRY_RUN; then echo "  DRY-RUN: $src → $dst"
  else mv "$src" "$dst" && echo "  OK: $src → $dst" && ((RENAMED++)) || { echo "  ERROR: $src → $dst"; ((ERRORS++)); }; fi
}

echo "=== VLM Rename from xlsx ==="
$DRY_RUN && echo "--- DRY RUN MODE ---"
echo ""
echo "--- Safe renames ---"
do_rename "highschooldxd_battle_001_en.png" "arifureta_gacha_001_jp.png"
do_rename "highschooldxd_battle_002_en.png" "highschooldxd_post_battle_001_en.png"
do_rename "highschooldxd_idle_overworld_001_jp.png" "highschooldxd_idle_001_jp.png"
do_rename "highschooldxd_idle_overworld_001_en.png" "highschooldxd_idle_002_en.png"
do_rename "highschooldxd_idle_overworld_002_jp.png" "highschooldxd_idle_002_jp.png"
do_rename "highschooldxd_idle_overworld_002_en.png" "highschooldxd_idle_003_en.png"
do_rename "highschooldxd_idle_overworld_003_jp.png" "highschooldxd_idle_003_jp.png"
do_rename "highschooldxd_idle_overworld_009_en.png" "highschooldxd_menu_popup_001_en.png"
do_rename "highschooldxd_idle_overworld_010_en.png" "highschooldxd_post_battle_002_en.png"
do_rename "highschooldxd_idle_overworld_011_en.png" "highschooldxd_idle_005_en.png"
do_rename "highschooldxd_idle_overworld_012_en.png" "highschooldxd_battle_005_en.png"
do_rename "highschooldxd_idle_overworld_013_en.png" "highschooldxd_battle_006_en.png"
do_rename "highschooldxd_idle_overworld_019_en.png" "highschooldxd_home_home_001_en.png"
do_rename "highschooldxd_idle_overworld_020_en.png" "highschooldxd_home_exchange_001_en.png"
do_rename "highschooldxd_idle_overworld_021_en.png" "highschooldxd_home_fest_001_en.png"
do_rename "highschooldxd_idle_overworld_022_en.png" "highschooldxd_gacha_007_en.png"
do_rename "highschooldxd_idle_overworld_071_en.png" "arifureta_gacha_002_jp.png"
do_rename "highschooldxd_idle_overworld_073_en.png" "highschooldxd_pre_battle_001_en.png"
do_rename "highschooldxd_idle_overworld_074_en.png" "highschooldxd_battle_007_en.png"
do_rename "highschooldxd_idle_overworld_075_en.png" "highschooldxd_battle_008_en.png"
do_rename "highschooldxd_idle_overworld_076_en.png" "highschooldxd_battle_009_en.png"
do_rename "highschooldxd_idle_overworld_078_en.png" "highschooldxd_campaign_001_en.png"
do_rename "highschooldxd_idle_overworld_079_en.png" "highschooldxd_post_battle_003_en.png"
do_rename "highschooldxd_menu_001_en.png" "highschooldxd_home_home_002_en.png"
do_rename "highschooldxd_menu_001_jp.png" "highschooldxd_home_home_001_jp.png"
do_rename "highschooldxd_post_battle_091_en.png" "highschooldxd_idle_overworld_005_en.png"
do_rename "screenshot (27).png" "arifureta_idle_001_jp.png"
do_rename "screenshot (28).png" "arifureta_idle_002_jp.png"
do_rename "screenshot (29).png" "arifureta_idle_003_jp.png"
do_rename "screenshot (30).png" "arifureta_idle_004_jp.png"
do_rename "screenshot (31).png" "arifureta_idle_005_jp.png"
do_rename "screenshot (32).png" "arifureta_idle_006_jp.png"
do_rename "screenshot (33).png" "arifureta_gacha_004_jp.png"
do_rename "screenshot (34).png" "arifureta_gacha_005_jp.png"
do_rename "screenshot (35).png" "arifureta_idle_007_jp.png"
do_rename "screenshot (36).png" "arifureta_idle_008_jp.png"
do_rename "screenshot (37).png" "arifureta_gacha_006_jp.png"
do_rename "screenshot (38).png" "arifureta_campaign_001_jp.png"
do_rename "screenshot (39).png" "arifureta_gacha_007_jp.png"
do_rename "screenshot (40).png" "arifureta_gacha_008_jp.png"
do_rename "screenshot (41).png" "arifureta_character_001_jp.png"
do_rename "screenshot (42).png" "arifureta_character_002_jp.png"
do_rename "screenshot (43).png" "arifureta_menu_001_jp.png"
do_rename "screenshot (44).png" "arifureta_menu_002_jp.png"
do_rename "screenshot (45).png" "arifureta_gacha_009_jp.png"
do_rename "screenshot (46).png" "arifureta_menu_003_jp.png"
do_rename "screenshot (47).png" "arifureta_idle_009_jp.png"
do_rename "screenshot (48).png" "arifureta_loading_001_en.png"
do_rename "screenshot (49).png" "arifureta_idle_001_en.png"
do_rename "screenshot (50).png" "arifureta_menu_001_en.png"
do_rename "screenshot (51).png" "arifureta_task_001_en.png"
do_rename "screenshot (52).png" "arifureta_task_002_en.png"
do_rename "screenshot (53).png" "arifureta_gear_001_en.png"
do_rename "screenshot (54).png" "arifureta_character_001_en.png"
do_rename "screenshot (55).png" "arifureta_gacha_001_en.png"
do_rename "screenshot (56).png" "arifureta_campaign_001_en.png"
do_rename "screenshot (57).png" "arifureta_campaign_002_en.png"
do_rename "screenshot (58).png" "arifureta_gem_shop_001_en.png"
do_rename "screenshot (59).png" "arifureta_idle_002_en.png"
do_rename "screenshot (60).png" "arifureta_idle_003_en.png"
do_rename "screenshot (61).png" "arifureta_idle_004_en.png"
do_rename "screenshot (62).png" "arifureta_idle_005_en.png"
do_rename "screenshot (63).png" "arifureta_idle_006_en.png"
do_rename "screenshot (64).png" "arifureta_idle_007_en.png"
do_rename "screenshot (65).png" "arifureta_idle_008_en.png"
do_rename "screenshot (66).png" "arifureta_idle_009_en.png"
do_rename "screenshot (67).png" "arifureta_idle_010_en.png"
do_rename "screenshot (77).png" "arifureta_idle_010_jp.png"
do_rename "screenshot (78).png" "arifureta_idle_011_jp.png"
do_rename "screenshot (79).png" "arifureta_idle_012_jp.png"
do_rename "screenshot (81).png" "arifureta_gear_001_jp.png"
do_rename "screenshot (82).png" "arifureta_gear_002_jp.png"
do_rename "screenshot (83).png" "arifureta_gear_003_jp.png"
do_rename "screenshot (84).png" "arifureta_gear_004_jp.png"
do_rename "screenshot (85).png" "arifureta_character_003_jp.png"
do_rename "screenshot (86).png" "arifureta_character_004_jp.png"
do_rename "screenshot (87).png" "arifureta_character_005_jp.png"
do_rename "screenshot (88).png" "arifureta_character_006_jp.png"
do_rename "screenshot (89).png" "arifureta_character_007_jp.png"
do_rename "screenshot (117).png" "highschooldxd_gacha_008_en.png"
do_rename "screenshot (118).png" "highschooldxd_gacha_009_en.png"
do_rename "screenshot (119).png" "highschooldxd_gacha_010_en.png"
do_rename "screenshot (127).png" "highschooldxd_idle_004_jp.png"
do_rename "screenshot (146).png" "highschooldxd_idle_005_jp.png"
do_rename "screenshot (147).png" "highschooldxd_battle_005_jp.png"
do_rename "screenshot (148).png" "highschooldxd_battle_006_jp.png"
do_rename "screenshot (159).png" "highschooldxd_post_battle_002_jp.png"
do_rename "screenshot (160).png" "highschooldxd_shop_001_jp.png"
do_rename "screenshot (162).png" "highschooldxd_shop_003_jp.png"
do_rename "screenshot (163).png" "highschooldxd_shop_002_jp.png"
do_rename "screenshot (164).png" "highschooldxd_shop_004_jp.png"
do_rename "screenshot (166).png" "highschooldxd_character_001_jp.png"
do_rename "screenshot (167).png" "highschooldxd_character_002_jp.png"
do_rename "screenshot (171).png" "highschooldxd_exchange_001_en.png"
do_rename "screenshot (172).png" "highschooldxd_shop_001_en.png"
do_rename "screenshot (173).png" "highschooldxd_shop_002_en.png"
do_rename "screenshot (174).png" "highschooldxd_shop_003_en.png"
do_rename "screenshot (175).png" "highschooldxd_shop_004_en.png"

echo ""
echo "--- Collision-safe renames (via temp names) ---"
do_rename "arifureta_gacha_003_jp.png" "_collision_tmp_0.png"
do_rename "highschooldxd_idle_overworld_005_en.png" "_collision_tmp_1.png"
do_rename "highschooldxd_pre_battle_001_en.png" "_collision_tmp_2.png"
do_rename "_collision_tmp_0.png" "highschooldxd_idle_001_en.png"
do_rename "_collision_tmp_1.png" "highschooldxd_idle_004_en.png"
do_rename "_collision_tmp_2.png" "arifureta_gacha_003_jp.png"

echo ""
echo "=== Summary ==="
$DRY_RUN && echo "  Dry run complete" && exit 0
echo "  Renamed: $RENAMED"
echo "  Skipped: $SKIPPED"
echo "  Errors:  $ERRORS"